version: "3"
services:
  springapp:
    build: .
    container_name: springapp
    ports:
      - 8000:8080
    restart: always
    depends_on:
      - db
  db:
    image: redis
    container_name: db
    ports:
      - 6379:6379